config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

search/urls.py
from django.urls import path, re_path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.SearchView.as_view(), name="search"),
    path('flights/', views.ResultsView.as_view(), name="flights"),
    path('flights/ajax', views.ResultsAjaxView.as_view(), name="flights_ajax"),
]

search/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms


class SearchForm(forms.Form):
    origin = forms.CharField(max_length=72, label="Miejsce wylotu", min_length=3)
    destination = forms.CharField(max_length=72, label="Miejsce przylotu")
    departure_date = forms.DateField(label="Data wylotu", widget=forms.DateInput(attrs={'type': 'date'}))
    return_date = forms.DateField(label="Data przylotu", widget=forms.DateInput(attrs={'type': 'date'}))

search/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import FormView, TemplateView

from search.forms import SearchForm


class SearchView(TemplateView):
    template_name = 'search/search.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form'] = SearchForm(self.request.GET) if self.request.GET else SearchForm()
        return ctx

    def get(self, request, *args, **kwargs):
        form = SearchForm(request.GET)

        if form.is_valid():
            return redirect(reverse('search:flights') + request.get_full_path()[1:])

        return super().get(request, *args, **kwargs)


class ResultsView(TemplateView):
    template_name = 'search/results.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form'] = SearchForm(self.request.GET) if self.request.GET else SearchForm()
        return ctx


class ResultsAjaxView(TemplateView):
    template_name = 'search/results_ajax.html'

search/templates/search/results.html
<h1>Results</h1>

<form action="" method="get">
    <h2>{{ form.errors }}</h2>


    {{ form.as_p }}
    <button type="submit">Search</button>

</form>

<div class="results">
    Wyniki:
    <div id="results"></div>
</div>

<script>
 const url = '{% url "search:flights_ajax" %}';

    const resultsRef = document.getElementById('results')
    const getData = async () => {
        const response = await fetch(url);
        console.log(response)
        const data = await response.text();

        resultsRef.innerHTML = resultsRef.innerHTML + data

        return response
    }
    const times = setInterval(() => {
        getData().then(response => {
            if (response.status === 402){
                clearInterval(times);
            }
        })
    }, 1000)

    setTimeout(() => {
        clearInterval(times)
    }, 10000)
</script>

search/templates/search/results_ajax.html
<div>
    <h2>Lot number 1234</h2>
</div>

search/templates/search/search.html
<h1>Search</h1>

<form action="" method="get">
    <h2>{{ form.errors }}</h2>



    {{ form.as_p }}
    <button type="submit">Search</button>

</form>